services:
  mongo:
    image: mongo:7
    container_name: aban-restaurant-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - aban_mongo_data:/data/db

volumes:
  aban_mongo_data:
